# src/main/resources/application.yml
server:
  port: 8080

spring:
  application:
    name: api-gateway   #  tên service hiển thị trên Eureka

  cloud:
    discovery:
      enabled: true     # bật discovery client
    service-registry:
      auto-registration:
        enabled: true   #  bật auto-register

    gateway:
      discovery:
        locator:
          enabled: true        # cho phép tự động định tuyến qua serviceId
          lower-case-service-id: true
      routes:
        - id: swagger-ui-self
          uri: forward:/
          predicates:
            - Path=/swagger-ui/**, /swagger-ui.html, /v3/api-docs/**, /v3/api-docs.yaml, /webjars/**

        # Rookie business
        - id: rookie-service
          uri: lb://rookie-service
          predicates:
            - Path=/api/rookie/**
          filters:
            - StripPrefix=2

        # Rookie OpenAPI docs
        - id: rookie-service-openapi
          uri: lb://rookie-service
          predicates:
            - Path=/api/rookie/v3/api-docs
          filters:
            - RewritePath=/api/rookie/v3/api-docs, /v3/api-docs

        # AI service business
        - id: ai-service
          uri: lb://ai-service
          predicates:
            - Path=/api/ai/**
          filters:
            - StripPrefix=2

        # AI OpenAPI docs
        - id: ai-service-openapi
          uri: lb://ai-service
          predicates:
            - Path=/api/ai/v3/api-docs
          filters:
            - RewritePath=/api/ai/v3/api-docs, /v3/api-docs

        # AR service business
        - id: ar-service
          uri: lb://ar-service
          predicates:
            - Path=/api/ar/**
          filters:
            - StripPrefix=2

        # AR OpenAPI docs
        - id: ar-service-openapi
          uri: lb://ar-service
          predicates:
            - Path=/api/ar/v3/api-docs
          filters:
            - RewritePath=/api/ar/v3/api-docs, /v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    disable-swagger-default-url: true
    config-url: /v3/api-docs/swagger-config
    urlsPrimaryName: rookie-service
    # Danh sách các spec truy cập QUA GATEWAY
    urls:
      - name: rookie-service
        url: /api/rookie/v3/api-docs
      - name: ai-service
        url: /api/ai/v3/api-docs
      - name: ar-service
        url: /api/ar/v3/api-docs
