# src/main/resources/application.yml
server:
  port: 8082

spring:
  application:
    name: story-diffusion-service   #  TÊN service hiển thị trên Eureka

  # Kết nối MongoDB Atlas
  data:
    mongodb:
      uri: mongodb+srv://tuyenctnse182129:123@cluster0.qp2no4l.mongodb.net/rookiedb?retryWrites=true&w=majority&appName=Rookie
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

  cloud:
    discovery:
      enabled: true
    service-registry:
      auto-registration:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
