package com.sep.aiservice.enums;

public enum StylePreset {
    _3D_MODEL, ANALOG_FILM, ANIME, CINEMATIC, COMIC_BOOK, DIGITAL_ART, ENHANCE,
    FANTASY_ART, ISOMETRIC, LINE_ART, LOW_POLY, MODELING_COMPOUND, NEON_PUNK,
    ORIGAMI, PHOTOGRAPHIC, PIXEL_ART, TILE_TEXTURE
}
