# src/main/resources/application.yml
# src/main/resources/application.yml
server:
  port: 8083

spring:
  application:
    name: google-speech-service   # tên service hiển thị trên Eureka

  # Kết nối MongoDB Atlas
  data:
    mongodb:
      uri: ${MONGODB_URI}
      auto-index-creation: false
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

  cache:
    type: redis
    redis:
      time-to-live: 600000        # TTL 10 phút
      cache-null-values: false
      use-key-prefix: true
      # key-prefix: story:        # (tùy chọn) để phân biệt key với service khác

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

  cloud:
    discovery:
      enabled: true
    service-registry:
      auto-registration:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    appname: google-speech-service
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

