server:
  port: ${AI_PORT:8082}

spring:
  application:
    name: ai-service

management:
  endpoints:
    web:
      exposure:
        include: health,info

redis:
  host: ${REDIS_HOST:redis}
  port: ${REDIS_PORT:6379}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://discovery-server:8761/eureka}
  instance:
    prefer-ip-address: true