server:
  port: ${AI_PORT:8082}

spring:
  application:
    name: ai-service
  redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}

management:
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://discovery-server:8761/eureka}
  instance:
    prefer-ip-address: true

stability:
  enabled: ${STABILITY_ENABLED:false}

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html