# src/main/resources/application.yml
server:
  port: 8082

spring:
  application:
    name: ai-service

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
    show-sql: true

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    timeout: 2000ms

  cache:
    type: redis
    redis:
      time-to-live: 600000
      cache-null-values: false
      use-key-prefix: true

  cloud:
    discovery:
      enabled: true
    service-registry:
      auto-registration:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    appname: ai-service
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

stability:
  base-url: https://api.stability.ai
  api-key: ${STABILITY_KEY}
  default-model: sd3.5-flash
  timeout-ms: 60000
  client:
    id: rookie-comics    # stability-client-id
    version: 1.0.0      # stability-client-version
  default-accept: image/*

storage:
  base-dir: /data/illustrations
  public-base-url: https://cdn.example.com/illustrations
