# src/main/resources/application.yml
server:
  port: 8082

spring:
  application:
    name: ai-service

  codec:
    max-in-memory-size: 256MB

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
    show-sql: true

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    timeout: 2000ms

  cache:
    type: redis
    redis:
      time-to-live: 600000
      cache-null-values: false
      use-key-prefix: true

  cloud:
    discovery:
      enabled: true
    service-registry:
      auto-registration:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    appname: ai-service
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

# Stability
stability:
  enabled: true
  base-url: https://api.stability.ai
  api-key: ${STABILITY_KEY}
  timeout-ms: 60000
  client:
    id: rookie-comics
    version: 1.0.0
  default-accept: image/*

#Gemini audio
gemini:
  api-key: ${GEMINI_API_KEY}
  base-url: https://generativelanguage.googleapis.com

# Firebase
storage:
  provider: firebase
  bucket: sep490-fa25se182.firebasestorage.app
  public-base-url: https://firebasestorage.googleapis.com
  # Chia folder:
  image-prefix: illustrations
  audio-prefix: audios

firebase:
  service-account-file: ${FIREBASE_CREDENTIALS_PATH}

